AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  powertools-java-samples

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    Runtime: java11
    MemorySize: 2048
    Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html

Resources:
  IdempotencyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: expiration
        Enabled: true
      BillingMode: PAY_PER_REQUEST

  PaymentQueue:
    Type: AWS::SQS::Queue
    Properties:
      SqsManagedSseEnabled: true
      VisibilityTimeout: 180
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt PaymentDeadLetterQueue.Arn
        maxReceiveCount: 3

  PaymentDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      SqsManagedSseEnabled: true

  PaymentFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: .
      Handler: software.amazon.lambda.samples.powertools.idempotency.sqs.payment.PaymentHandler::handleRequest
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          POWERTOOLS_SERVICE_NAME: payment
          IDEMPOTENCY_TABLE: !Ref IdempotencyTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref IdempotencyTable
        - SQSPollerPolicy:
            QueueName: !GetAtt PaymentQueue.QueueName
      Events:
        Payment:
          Type: SQS # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Queue: !GetAtt PaymentQueue.Arn
            BatchSize: 10
            Enabled: true
            MaximumBatchingWindowInSeconds: 10
Outputs:
  PaymentsQueueUrl:
    Description: "Payment SQS Queue URL"
    Value: !Ref PaymentQueue